### ISSUE TITLE
[IOS] Not receiving incoming call for IOS

### ISSUE THREAD

**Issue by tanmoy27112000** [cybex-dev/twilio_voice#196]
### Issue Summary

I am able to perform outgoing calls but not able to receive incoming call for iOS

Logs:

`Successfully registered for VoIP push notifications.`

**Comment by cybex-dev** [comment]
Hi @tanmoy27112000,

Have you been able to receive atleast one working call throughout the time of development on the current app on your iOS device?

**Comment by tanmoy27112000** [comment]
Yes we use to get incoming calls earlier but now only outgoing calls are working

**Comment by tanmoy27112000** [comment]
@cybex-dev this is very critical , we have regenerated the certificates and confirmed all possible areas, still no incoming calls.

**Comment by cybex-dev** [comment]
> Yes we use to get incoming calls earlier but now only outgoing calls are working

@tanmoy27112000 

I see, so it did work but now doesn't. 

Please provide more information with regards to:
- Did you update `twilio_voice` package, and when roughly?
- If yes to the above, from which package version did you upgrade from, and which package version did you upgrade to? i.e. `0.0.9 -> 0.1.0`

**Comment by tanmoy27112000** [comment]
current version is:
```
twilio_voice:
    dependency: "direct main"
    description:
      name: twilio_voice
      sha256: c9b0396a1b3d6ed08998da8299a4e7be16d4862c6e3b74cf2c9d901a8a2c190e
      url: "https://pub.dev"
    source: hosted
    version: "0.1.1"
```

the older version was 0.1.0 according to by GitHub commits
